# Generated by Django 4.2 on 2023-04-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtxt', models.CharField(max_length=200)),
                ('qdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_txt', models.CharField(max_length=150)),
                ('votes', models.IntegerField(default=0)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.quest')),
            ],
        ),
    ]
